select* from customer limit 20

-- Q1: Total revenue generated by male vs female customers:

select gender, SUM (purchase_amount) AS revenue 
from customer
group by gender 

--Q2: Which customers used discount but still spent more than the average amount?:

select customer_id , purchase_amount 
from customer
where discount_applies = 'YES' and purchase_amount = SELECT(AVG(purchase_amount) from customer)

--Q3: Which are the top 5 products with the highest average review rating?:

select item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4: Compare the average purchase amounts between standard and express shipping :

select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5: Do subscribed customers spend more? Compare average spend and total revenue between suscribers and non subscriber:

select subscription_status,
COUNT(cust)

